### ISSUE TITLE
Request: Hybrid Kubernetes Cluster Support

### ISSUE THREAD

**Issue by jonstelly** [portainer/portainer-k8s#3]
I'd like to test this out on a hybrid Kubernetes cluster, but there are a couple issues:

1) linux-arm docker tag shows OS/Arch as linux/amd64 - [link](https://hub.docker.com/r/portainer/portainer-k8s-beta/tags).  The image still runs on arm but if you can fix the OS/Arch for that image, you could then do something like:

```
docker manifest create portainer/portainer-k8s-beta:latest portainer/portainer-k8s-beta:linux-arm portainer/portainer-k8s-beta:linux-amd64
docker push portainer/portainer-k8s-beta:latest
```

NOTE: As something to look into, [docker buildx](https://docs.docker.com/buildx/working-with-buildx/) makes it pretty easy to build and publish multi-arch docker images.

2) No multi-arch tag: If you fix the above issue, you could then change all the YAML files to use `portainer/portainer-k8s-beta:latest` and docker would pull the image for the correct OS and architecture.

Without that, if I want to deploy portainer-k8s-beta to a hybrid kube (arm64 and amd64) I have to decide at deployment time which platform I want to run on and modify the YAML files to specify the correct image, and include a node affinity to ensure pods only get scheduled on the correct architecture with something like:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
```
